### ISSUE TITLE
Windows Defender might be false-reporting.

### ISSUE THREAD

**Issue by IngwiePhoenix** [TalonSabre/PKLumiHex#2]
**Describe the bug**
This should explain:
![image](https://github.com/TalonSabre/PKLumiHex/assets/2893716/d02357aa-6b49-427c-ae1d-e0e3be9e7cdf)

It targets the `.zip` file.

**To Reproduce**
1. Download the latest (0.2.3) zip
2. Windows Defender should pop a warning immediately.

**Expected behavior**
That WD doesn't bother me.

**Screenshots**
Above

**Additional context**
I am on Windows 10 - and pretty sure this is a false-positive. But, I wanted to point this out, just in case.

**Comment by OMGitsMatt45** [comment]
It's the same on windows 11

**Comment by TalonSabre** [comment]
I'm assuming it's fine now, but I'm putting this here for my own reference, and everyone else's:
I changed the .zip contents from just a packaged .exe to a release build from the Visual Studio project folder the same day this was reported.
Haven't heard this reported since.

It seems Windows doesn't like the packaged, standalone .exe file for some reason.
Most likely because it's not signed with a certificate, which would require monetary payment to fix and maintain. It's a monthly charge as I remember.

If it still gives you fits, there's something else going on. 
This app was not built to contain a virus. I pledge my life on that.
It shouldn't be giving any more trouble though.
