### ISSUE TITLE
Confusing/nonfunctional Pokédex editor

### ISSUE THREAD

**Issue by Ammako** [TalonSabre/PKLumiHex#4]
**Describe the bug**
Pokédex editor doesn't seem to properly reflect what I see in-game, and edits in the Pokédex editor don't seem to be properly reflected in-game.

Example: a lot of Pokémon that I've seen in-game, just show as "Seen" in the Pokédex editor but no genders actually marked as seen. Some are "Seen" with one or both genders marked as seen. Some other Pokémon show certain genders as Seen despite not actually being marked as Seen (including a bunch of Gen 5-9 Pokémon.) It's hard to tell what's actually supposed to be correct if you wanted to make manual edits.

If I use the editor to set the entire dex as Seen, even though the list in-game shows every Pokémon, the only entries that are actually accessible are the ones that were legitimately encountered in-game. Same if I set the entire Pokédex to Caught, the only entries that can be viewed are the ones which were legitimately Seen or Caught in-game, even though they all show up as Caught in the Pokédex in-game.

If I Save a Pokémon into a slot, then SetUpdateDex on SlotWrite sets the flags automatically in the Pokédex editor, which doesn't actually work; _unless_ it's a male shiny Pokémon, then it works just fine in-game. Setting Male Shiny as Seen in the Pokédex editor makes the Pokédex entry functional and accessible, unless the Pokémon in question is female-only. Male-only, genderless and every other gender ratio entries seem to work fine in-game as long as Male Shiny is set as Seen. For female-only Pokémon, it doesn't matter if you set the Male Shiny as seen, the entry in-game doesn't work.

**To Reproduce**
1. Use Pokédex editor in PKLumiHex after playing a little while in-game
2. Observe how state differs between different species, with no apparent rhyme or reason
3. Try to set the entire Pokédex as Seen and/or Caught, and view the changes in-game

**Expected behavior**
Pokédex editor should read/write data to and from the right places in the save data so that everything is consistent between editor and in-game.

**Screenshots**
N/A

**Additional context**

2.0.2F for what it's worth.

Probably might need to redo the interface for the Pokédex editor, given that the format for Pokédex data in Luminescent is very different from the original. The current interface options aren't really relevant nor suitable for Luminescent.

(One more thing: given that Pokédex entries in languages other than English aren't really functional in-game, it might be worth making it so English is the only language that ever gets set, even when importing foreign language Pokémon.)

**Comment by TalonSabre** [comment]
This issue has to do with the way the save files were made in 2.0.2F. 
I believe the structure for it is correct. 
It does look wrong in pklumi though, and in my test saves, added seen data does not function.
I haven't heard this being echoed much, either, so I was under the impression a previously-edited-with-an-old-version-of-pklumi-that-has-incorrect-dex-data-format save was the issue.

For clarity: Is this a fresh, or otherwise unaltered save before using the dex editor?
I also find it odd that a male shiny setting makes it function.

Luckily for us (or unluckily if for some reason you stick to the old one), Re:Lumi is around the corner, and the dex structure will be the same as vanilla, so this won't be an issue in the future.
I apologize for the extremely delayed response, I have been inactive the past few months.
